// Autogenerated

#import "MyProgram.h"
#import <OpenGLPlus/GLPProgram+XML.h>
#import <OpenGLPlus/GLPProgram+ObjectLabel.h>

@interface MyProgram ()

@property (nonatomic, assign, readwrite) GLint positionLocation;
@property (nonatomic, assign, readwrite) GLint texcoordLocation;

@property (nonatomic, assign, readwrite) GLint alphaLocation;
@property (nonatomic, assign, readwrite) GLint textureLocation;
@property (nonatomic, assign, readwrite) GLint transformLocation;

@end

@implementation MyProgram

+ (instancetype)programWithError:(NSError **)error
{
	MyProgram *program = [self linkedProgramWithXMLResource:@"MyProgram" bundle:nil error:error];
	program.objectLabel = @"MyProgram";
	
	program.positionLocation = [program attributeLocation:@"position"];
	program.texcoordLocation = [program attributeLocation:@"texcoord"];
	
	program.alphaLocation = [program uniformLocation:@"alpha"];
	program.textureLocation = [program uniformLocation:@"texture"];
	program.transformLocation = [program uniformLocation:@"transform"];
	
	return program;
}

- (void)setAlpha:(GLfloat)alpha
{
	[self setUniform:self.alphaLocation floatValue:alpha];
}

- (void)setTexture:(GLint)texture
{
	[self setUniform:self.textureLocation intValue:texture];
}

- (void)setTransform:(const GLfloat[16])transform
{
	[self setUniform:self.transformLocation matrix4Value:transform];
}

@end
